/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class TestJNIInstanceVariable */

#ifndef _Included_TestJNIInstanceVariable
#define _Included_TestJNIInstanceVariable
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     TestJNIInstanceVariable
 * Method:    modifyInstanceVariable
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_TestJNIInstanceVariable_modifyInstanceVariable
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
