/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class TestJNIString */

#ifndef _Included_TestJNIString
#define _Included_TestJNIString
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     TestJNIString
 * Method:    sayHello
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_TestJNIString_sayHello
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
