/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class TestJNIStaticVariable */

#ifndef _Included_TestJNIStaticVariable
#define _Included_TestJNIStaticVariable
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     TestJNIStaticVariable
 * Method:    modifyStaticVariable
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_TestJNIStaticVariable_modifyStaticVariable
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
